import { useEffect, useMemo, useRef, useState } from 'react';
import { useLocation } from 'wouter';
import { ArrowLeft, Bell, Check, CheckCheck, Inbox, MessageSquare, Package, Search, Send, ShieldCheck, Store, Trash2 } from 'lucide-react';
import './seller-communications.css';
import { ConfirmDialog, type ConfirmSpec } from './confirm-dialog';
import { useLocale } from '../lib/i18n/locale-context';

const API = 'https://nzanila-api-server.nzanilaexpress.workers.dev';
const authHeaders = (json = false): Record<string, string> => ({ ...(json ? { 'Content-Type': 'application/json' } : {}), Authorization: `Bearer ${localStorage.getItem('sc_token') || ''}` });
const initials = (name: string) => name.split(/\s+/).filter(Boolean).slice(0, 2).map(part => part[0]).join('').toUpperCase() || 'U';
const relativeTime = (value?: string) => { if (!value) return ''; const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); if (minutes < 1) return 'now'; if (minutes < 60) return `${minutes}m ago`; if (minutes < 1440) return `${Math.floor(minutes / 60)}h ago`; return `${Math.floor(minutes / 1440)}d ago`; };
function Avatar({ party }: { party?: { name?: string; avatar?: string } }) {
  const name = party?.name || 'User';
  return <span className="sc-avatar blue">{party?.avatar ? <img src={party.avatar} alt="" loading="lazy" /> : initials(name)}</span>;
}
function Empty({ title, text }: { title: string; text: string }) { return <div className="sc-empty"><span><Inbox size={28} /></span><h3>{title}</h3><p>{text}</p></div>; }
type Conversation = { id: number; otherParty?: { id: number; name: string; avatar?: string }; lastMessage?: string; lastMessageAt?: string; unreadCount?: number; storeId?: number; storeName?: string; storeSlug?: string; storeUrl?: string; storeLogo?: string };
type ChatMessage = { id: number; senderId: number; body: string; createdAt: string };

export function MessagesPage() {
  const { tr } = useLocale();
  const requestedBuyerId = Number(new URLSearchParams(window.location.search).get('buyerId')) || null;
  const [items, setItems] = useState<Conversation[]>([]); const [selected, setSelected] = useState<number | null>(null); const [messages, setMessages] = useState<ChatMessage[]>([]); const [draft, setDraft] = useState(''); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All'); const [storeFilter, setStoreFilter] = useState<number | 'all'>('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [sending, setSending] = useState(false); const bottom = useRef<HTMLDivElement>(null); const scrollHistoryToBottom = () => { const history = bottom.current?.parentElement; if (history) history.scrollTop = history.scrollHeight; }; const scrollToBottomSoon = () => window.setTimeout(scrollHistoryToBottom, 250); const [confirm, setConfirm] = useState<ConfirmSpec | null>(null);
  const loadConversations = async () => { try { const response = await fetch(`${API}/api/conversations`, { headers: authHeaders() }); if (!response.ok) throw new Error('Could not load conversations'); const data = await response.json(); const next = Array.isArray(data) ? data : []; setItems(next); setSelected(current => requestedBuyerId ? next.find((item: Conversation) => item.otherParty?.id === requestedBuyerId)?.id || current : current && next.some((item: Conversation) => item.id === current) ? current : next[0]?.id || null); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not load conversations'); } finally { setLoading(false); } };
  const loadMessages = async (id: number) => { const response = await fetch(`${API}/api/conversations/${id}`, { headers: authHeaders() }); if (response.ok) setMessages(await response.json()); };
  useEffect(() => { void loadConversations(); const timer = window.setInterval(() => void loadConversations(), 10000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { if (!selected) { setMessages([]); return; } void loadMessages(selected); const timer = window.setInterval(() => void loadMessages(selected), 8000); return () => window.clearInterval(timer); }, [selected]);
  // The keyboard shrinks the visual viewport; follow it so the newest message and the composer stay visible.
  useEffect(() => { const viewport = window.visualViewport; if (!viewport) return; const follow = () => window.setTimeout(scrollHistoryToBottom, 60); viewport.addEventListener('resize', follow); return () => viewport.removeEventListener('resize', follow); }, []);
  useEffect(() => { bottom.current?.scrollIntoView({ block: 'nearest' }); }, [messages.length]);
    // The distinct stores actually present in the inbox — a seller with one store never
  // sees this row at all, so the extra UI only appears once it is actually needed.
  const stores = useMemo(() => {
    const seen = new Map<number, { id: number; name: string; logo?: string }>();
    for (const item of items) if (item.storeId && !seen.has(item.storeId)) seen.set(item.storeId, { id: item.storeId, name: item.storeName || 'Store', logo: item.storeLogo });
    return [...seen.values()];
  }, [items]);
  const visible = useMemo(() => items.filter(item =>
    (filter !== 'Unread' || Number(item.unreadCount) > 0) &&
    (storeFilter === 'all' || item.storeId === storeFilter) &&
    `${item.otherParty?.name || ''} ${item.storeName || ''} ${item.lastMessage || ''}`.toLowerCase().includes(query.toLowerCase())
  ), [items, filter, storeFilter, query]);
  const active = items.find(item => item.id === selected);
  const send = async (event: React.FormEvent) => { event.preventDefault(); if (!selected || !draft.trim() || sending) return; setSending(true); try { const response = await fetch(`${API}/api/conversations/${selected}`, { method: 'POST', headers: authHeaders(true), body: JSON.stringify({ message: draft.trim() }) }); if (response.ok) { setDraft(''); await loadMessages(selected); await loadConversations(); } } finally { setSending(false); } }; const removeConversation = async () => { if (!selected || sending) return; setSending(true); try { const response = await fetch(`${API}/api/conversations/${selected}`, { method: 'DELETE', headers: authHeaders() }); if (response.ok) { setItems(old => old.filter(item => item.id !== selected)); setSelected(null); setMessages([]); } } finally { setSending(false); } }; const deleteMessage = async (messageId: number) => { if (!selected || sending) return; setSending(true); try { const response = await fetch(`${API}/api/conversations/${selected}/messages/${messageId}`, { method: 'DELETE', headers: authHeaders() }); if (response.ok) { await loadMessages(selected); await loadConversations(); } } finally { setSending(false); } };
  const startConversation = async (event: React.FormEvent) => { event.preventDefault(); if (!requestedBuyerId || !draft.trim() || sending) return; setSending(true); try { const response = await fetch(`${API}/api/conversations`, { method: 'POST', headers: authHeaders(true), body: JSON.stringify({ buyerId: requestedBuyerId, message: draft.trim() }) }); if (response.ok) { const data = await response.json(); setDraft(''); await loadConversations(); setSelected(Number(data.conversationId)); } } finally { setSending(false); } };

  const askRemoveConversation = () => setConfirm({
    title: 'Delete this conversation?',
    description: 'The whole thread disappears from your inbox. The buyer keeps their copy.',
    confirmLabel: 'Delete conversation', tone: 'danger', onConfirm: removeConversation,
  });

  const askDeleteMessage = (messageId: number) => setConfirm({
    title: 'Delete this message?',
    description: 'It is removed from the conversation for both of you.',
    confirmLabel: 'Delete message', tone: 'danger', onConfirm: () => deleteMessage(messageId),
  });

  return <div className="sc-comms sc-messenger"><div className={`sc-inbox ${selected ? 'sc-chat-open' : ''}`}>
    <section className="sc-conversations" aria-label={tr("sc.conversations")}><div className="sc-inbox-heading"><h3>Chats {items.reduce((sum, item) => sum + Number(item.unreadCount || 0), 0) > 0 && <span className="sc-count">{items.reduce((sum, item) => sum + Number(item.unreadCount || 0), 0)}</span>}</h3><MessageSquare size={20} /></div><label className="sc-search"><Search size={17} /><input aria-label={tr("sc.search-buyers-or-products")} value={query} onChange={event => setQuery(event.target.value)} placeholder={tr("sc.search-buyers-or-products")} /></label>{stores.length > 1 && <label className="sc-store-filter"><Store size={14} /><select aria-label={tr('store.allStores')} value={storeFilter} onChange={event => setStoreFilter(event.target.value === 'all' ? 'all' : Number(event.target.value))}><option value="all">{tr('store.allStores')}</option>{stores.map(store => <option key={store.id} value={store.id}>{store.name}</option>)}</select></label>}<div className="sc-tabs">{['All', 'Unread'].map(tab => <button key={tab} aria-pressed={filter === tab} className={filter === tab ? 'active' : ''} onClick={() => setFilter(tab)}>{tab}</button>)}</div><div className="sc-conversation-list">{loading ? <Empty title={tr("sc.loading-conversations")} text="Checking your live inbox…" /> : error ? <Empty title={tr("sc.inbox-unavailable")} text={error} /> : visible.map(item => <button className={`sc-conversation ${selected === item.id ? 'selected' : ''}`} key={item.id} onClick={() => setSelected(item.id)} aria-pressed={selected === item.id}><Avatar party={item.otherParty} /><span className="sc-conversation-body"><span className="sc-conversation-top"><strong>{item.otherParty?.name || 'Buyer'}</strong><small>{relativeTime(item.lastMessageAt)}</small></span>{item.storeId && <span className="sc-store-tag">{item.storeLogo ? <img src={item.storeLogo} alt="" loading="lazy" /> : <Store size={11} />}{item.storeName || tr('store.title')}</span>}<span className="sc-snippet">{item.lastMessage || 'No messages yet'}</span></span>{Number(item.unreadCount) > 0 && <span className="sc-unread-dot" />}</button>)}{!loading && !error && !visible.length && <Empty title={tr("sc.no-conversations")} text="Buyer messages will appear here when someone contacts your store." />}</div><div className="sc-inbox-footer"><ShieldCheck size={15} />{tr('sc.live-conversations-from-your-account')}</div></section>
    <section className="sc-thread" aria-label={tr("sc.conversation")}>{active ? <><header className="sc-thread-header"><button className="sc-icon-button sc-mobile-back" aria-label={tr("sc.back-to-inbox")} onClick={() => setSelected(null)}><ArrowLeft size={20} /></button><Avatar party={active.otherParty} /><div className="sc-thread-person"><h3>{active.otherParty?.name || 'Buyer'}</h3><p>{active.storeId ? <>{active.storeLogo && <img className="sc-thread-store-logo" src={active.storeLogo} alt="" loading="lazy" />}{active.storeName || tr('store.title')}</> : tr('sc.noStoreOnConversation')}</p></div></header><div className="sc-message-history" role="log" aria-live="polite">{messages.map(message => <div key={message.id} className={`sc-message ${message.senderId === active.otherParty?.id ? '' : 'own'}`}><div className="sc-message-row"><div className="sc-bubble">{message.body}</div>{message.senderId !== active.otherParty?.id && <button type="button" className="sc-message-delete" title={tr("sc.delete-message")} aria-label={tr("sc.delete-message")} onClick={() => askDeleteMessage(message.id)}><Trash2 size={13} /></button>}</div><span className="sc-message-time">{message.senderId === active.otherParty?.id ? '' : 'You · '}{relativeTime(message.createdAt)}{message.senderId !== active.otherParty?.id && <Check size={12} />}</span></div>)}<div ref={bottom} />{!messages.length && <Empty title={tr("sc.no-messages-yet")} text="Send the first reply to this buyer." />}</div><form className="sc-composer" onSubmit={send}><div className="sc-compose-box"><textarea aria-label={tr("sc.write-a-reply")} placeholder={`Reply to ${active.otherParty?.name || 'buyer'}…`} maxLength={4000} rows={1} onFocus={scrollToBottomSoon} value={draft} onChange={event => setDraft(event.target.value)} /><div><button aria-label={tr("sc.send-message")} title={tr("sc.send-message")} className="sc-button primary" disabled={sending || !draft.trim()} type="submit"><Send size={19} /></button></div></div></form></> : requestedBuyerId ? <><header className="sc-thread-header"><span className="sc-avatar blue">B</span><div className="sc-thread-person"><h3>{tr('sc.buyer')}</h3><p>{tr('sc.start-a-live-conversation')}</p></div></header><div className="sc-message-history"><Empty title={tr("sc.start-the-conversation")} text="Send a message to this buyer about the order." /></div><form className="sc-composer" onSubmit={startConversation}><div className="sc-compose-box"><textarea aria-label={tr("sc.write-a-message")} placeholder={tr("sc.write-a-message-to-the-buyer")} maxLength={4000} rows={1} onFocus={scrollToBottomSoon} value={draft} onChange={event => setDraft(event.target.value)} /><div><button aria-label={tr("sc.send-message")} className="sc-button primary" disabled={sending || !draft.trim()} type="submit"><Send size={19} /></button></div></div></form></> : <Empty title={tr("sc.your-live-inbox")} text="Select a buyer conversation to read and reply." />}</section>
  </div><ConfirmDialog spec={confirm} onClose={() => setConfirm(null)} /></div>;
}

type Notification = { id: number; type: string; title: string; body: string; link?: string; createdAt: string; readAt?: string | null };
export function NotificationsPage({ onNavigate }: { onNavigate?: () => void } = {}) {
  const { tr } = useLocale();
  const [, setLocation] = useLocation();
  const [items, setItems] = useState<Notification[]>([]); const [query, setQuery] = useState(''); const [unreadOnly, setUnreadOnly] = useState(false); const [loading, setLoading] = useState(true);
  const autoMarkedRef = useRef(false);
  // Ids that were unread when this view opened. Opening clears the badge server-side, but
  // these stay highlighted for the session so you can still see what's new (Facebook does this).
  const [newIds, setNewIds] = useState<Set<number>>(() => new Set());
  const load = async () => { const response = await fetch(`${API}/api/notifications`, { headers: authHeaders() }); if (response.ok) { const data = await response.json(); setItems(Array.isArray(data.notifications) ? data.notifications : []); } setLoading(false); };
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 10000); return () => window.clearInterval(timer); }, []);
  const isNew = (item: Notification) => newIds.has(item.id) || !item.readAt;
  const unread = items.filter(isNew).length; const visible = items.filter(item => (!unreadOnly || isNew(item)) && `${item.title} ${item.body} ${item.type}`.toLowerCase().includes(query.toLowerCase()));
  const markRead = async (id: number) => { setNewIds(old => { const next = new Set(old); next.delete(id); return next; }); await fetch(`${API}/api/notifications/read`, { method: 'POST', headers: authHeaders(true), body: JSON.stringify({ id }) }); setItems(old => old.map(item => item.id === id ? { ...item, readAt: new Date().toISOString() } : item)); };
  const markAll = async () => { setNewIds(new Set()); await fetch(`${API}/api/notifications/read-all`, { method: 'POST', headers: authHeaders(true) }); setItems(old => old.map(item => ({ ...item, readAt: new Date().toISOString() }))); };
  // On open: clear the unread badge server-side, but remember which were new so they stay highlighted.
  useEffect(() => { if (loading || autoMarkedRef.current) return; autoMarkedRef.current = true; const unreadIds = items.filter(item => !item.readAt).map(item => item.id); if (!unreadIds.length) return; setNewIds(new Set(unreadIds)); void fetch(`${API}/api/notifications/read-all`, { method: 'POST', headers: authHeaders(true) }).then(() => setItems(old => old.map(item => ({ ...item, readAt: item.readAt || new Date().toISOString() })))); }, [loading]);
  const openItem = (item: Notification) => { if (isNew(item)) void markRead(item.id); if (item.link) { setLocation(item.link); onNavigate?.(); } };
  return <div className="sc-comms sc-notifications notification-center"><div className="nc-heading"><div><div className="nc-kicker"><Bell size={14} />{tr('sc.activity-center')}</div><h2>{tr('sc.notifications')}<span>{unread}</span></h2><p>{tr('sc.your-live-orders-conversations-and-store-upd')}</p></div><button className="nc-mark-all" disabled={!unread} onClick={markAll}><CheckCheck size={17} />{tr('sc.mark-all-as-read')}</button></div><section className="nc-panel" aria-label={tr("sc.notifications")}><div className="nc-toolbar"><div className="nc-view-switch"><button aria-pressed={!unreadOnly} className={!unreadOnly ? 'active' : ''} onClick={() => setUnreadOnly(false)}>{tr('sc.all-updates')}</button><button aria-pressed={unreadOnly} className={unreadOnly ? 'active' : ''} onClick={() => setUnreadOnly(true)}>{tr('sc.unread')}<span>{unread}</span></button></div><label className="sc-search"><Search size={17} /><input aria-label={tr("sc.search-notifications")} placeholder={tr("sc.search-notifications-2")} value={query} onChange={event => setQuery(event.target.value)} /></label></div><div className="nc-group"><div className="nc-group-label">{tr('sc.live-activity')}<span>{visible.length} updates</span></div>{loading ? <Empty title={tr("sc.loading-notifications")} text="Checking your live account activity…" /> : visible.map(item => <article key={item.id} className={`nc-item ${isNew(item) ? 'unread' : ''} ${item.link ? 'nc-item-linked' : ''}`} onClick={() => openItem(item)}><span className="nc-event-icon blue">{item.type === 'order' ? <Package size={20} /> : <MessageSquare size={20} />}</span><div className="nc-item-content"><div className="nc-item-title"><h3>{item.title}</h3>{isNew(item) && <span className="nc-new" aria-label={tr("sc.unread")} />}</div><p>{item.body}</p><div className="nc-item-bottom"><span className="nc-category">{item.type}</span><span className="nc-time">{relativeTime(item.createdAt)}</span></div></div><button className={`nc-read-button ${isNew(item) ? '' : 'is-read'}`} title={isNew(item) ? 'Mark as read' : 'Read'} aria-label={tr("sc.mark-notification-as-read")} onClick={event => { event.stopPropagation(); void markRead(item.id); }}><Check size={16} /></button></article>)}{!loading && !visible.length && <Empty title={unreadOnly ? 'You are all caught up' : 'No notifications'} text="Real account activity will appear here." />}</div></section><p className="nc-endnote"><ShieldCheck size={14} />{tr('sc.live-notifications-from-your-seller-account')}</p></div>;
}
