import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, Bell, Check, CheckCheck, Inbox, MessageSquare, Package, Search, Send, ShieldCheck, Trash2 } from 'lucide-react';
import './seller-communications.css';

const API = 'https://nzanila-api-server.nzanilaexpress.workers.dev';
const authHeaders = (json = false): Record<string, string> => ({ ...(json ? { 'Content-Type': 'application/json' } : {}), Authorization: `Bearer ${localStorage.getItem('sc_token') || ''}` });
const initials = (name: string) => name.split(/\s+/).filter(Boolean).slice(0, 2).map(part => part[0]).join('').toUpperCase() || 'U';
const relativeTime = (value?: string) => { if (!value) return ''; const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); if (minutes < 1) return 'now'; if (minutes < 60) return `${minutes}m ago`; if (minutes < 1440) return `${Math.floor(minutes / 60)}h ago`; return `${Math.floor(minutes / 1440)}d ago`; };
function Empty({ title, text }: { title: string; text: string }) { return <div className="sc-empty"><span><Inbox size={28} /></span><h3>{title}</h3><p>{text}</p></div>; }
type Conversation = { id: number; otherParty?: { id: number; name: string }; lastMessage?: string; lastMessageAt?: string; unreadCount?: number };
type ChatMessage = { id: number; senderId: number; body: string; createdAt: string };

export function MessagesPage() {
  const requestedBuyerId = Number(new URLSearchParams(window.location.search).get('buyerId')) || null;
  const [items, setItems] = useState<Conversation[]>([]); const [selected, setSelected] = useState<number | null>(null); const [messages, setMessages] = useState<ChatMessage[]>([]); const [draft, setDraft] = useState(''); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [sending, setSending] = useState(false); const bottom = useRef<HTMLDivElement>(null);
  const loadConversations = async () => { try { const response = await fetch(`${API}/api/conversations`, { headers: authHeaders() }); if (!response.ok) throw new Error('Could not load conversations'); const data = await response.json(); const next = Array.isArray(data) ? data : []; setItems(next); setSelected(current => requestedBuyerId ? next.find((item: Conversation) => item.otherParty?.id === requestedBuyerId)?.id || current : current && next.some((item: Conversation) => item.id === current) ? current : next[0]?.id || null); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not load conversations'); } finally { setLoading(false); } };
  const loadMessages = async (id: number) => { const response = await fetch(`${API}/api/conversations/${id}`, { headers: authHeaders() }); if (response.ok) setMessages(await response.json()); };
  useEffect(() => { void loadConversations(); const timer = window.setInterval(() => void loadConversations(), 10000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { if (!selected) { setMessages([]); return; } void loadMessages(selected); const timer = window.setInterval(() => void loadMessages(selected), 8000); return () => window.clearInterval(timer); }, [selected]);
  useEffect(() => { bottom.current?.scrollIntoView({ block: 'nearest' }); }, [messages.length]);
  const visible = useMemo(() => items.filter(item => (filter !== 'Unread' || Number(item.unreadCount) > 0) && `${item.otherParty?.name || ''} ${item.lastMessage || ''}`.toLowerCase().includes(query.toLowerCase())), [items, filter, query]);
  const active = items.find(item => item.id === selected);
  const send = async (event: React.FormEvent) => { event.preventDefault(); if (!selected || !draft.trim() || sending) return; setSending(true); try { const response = await fetch(`${API}/api/conversations/${selected}`, { method: 'POST', headers: authHeaders(true), body: JSON.stringify({ message: draft.trim() }) }); if (response.ok) { setDraft(''); await loadMessages(selected); await loadConversations(); } } finally { setSending(false); } }; const removeConversation = async () => { if (!selected || sending || !window.confirm('Delete this conversation?')) return; setSending(true); try { const response = await fetch(`${API}/api/conversations/${selected}`, { method: 'DELETE', headers: authHeaders() }); if (response.ok) { setItems(old => old.filter(item => item.id !== selected)); setSelected(null); setMessages([]); } } finally { setSending(false); } }; const deleteMessage = async (messageId: number) => { if (!selected || sending || !window.confirm('Delete this message?')) return; setSending(true); try { const response = await fetch(`${API}/api/conversations/${selected}/messages/${messageId}`, { method: 'DELETE', headers: authHeaders() }); if (response.ok) { await loadMessages(selected); await loadConversations(); } } finally { setSending(false); } };
  const startConversation = async (event: React.FormEvent) => { event.preventDefault(); if (!requestedBuyerId || !draft.trim() || sending) return; setSending(true); try { const response = await fetch(`${API}/api/conversations`, { method: 'POST', headers: authHeaders(true), body: JSON.stringify({ buyerId: requestedBuyerId, message: draft.trim() }) }); if (response.ok) { const data = await response.json(); setDraft(''); await loadConversations(); setSelected(Number(data.conversationId)); } } finally { setSending(false); } };
  return <div className="sc-comms sc-messenger"><div className={`sc-inbox ${selected ? 'sc-chat-open' : ''}`}>
    <section className="sc-conversations" aria-label="Conversations"><div className="sc-inbox-heading"><h3>Chats <span className="sc-count">{items.reduce((sum, item) => sum + Number(item.unreadCount || 0), 0)}</span></h3><MessageSquare size={20} /></div><label className="sc-search"><Search size={17} /><input aria-label="Search buyers or products" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search buyers or products" /></label><div className="sc-tabs">{['All', 'Unread'].map(tab => <button key={tab} aria-pressed={filter === tab} className={filter === tab ? 'active' : ''} onClick={() => setFilter(tab)}>{tab}</button>)}</div><div className="sc-conversation-list">{loading ? <Empty title="Loading conversations" text="Checking your live inbox…" /> : error ? <Empty title="Inbox unavailable" text={error} /> : visible.map(item => <button className={`sc-conversation ${selected === item.id ? 'selected' : ''}`} key={item.id} onClick={() => setSelected(item.id)} aria-pressed={selected === item.id}><span className="sc-avatar blue">{initials(item.otherParty?.name || 'User')}</span><span className="sc-conversation-body"><span className="sc-conversation-top"><strong>{item.otherParty?.name || 'Buyer'}</strong><small>{relativeTime(item.lastMessageAt)}</small></span><span className="sc-company">Buyer conversation</span><span className="sc-snippet">{item.lastMessage || 'No messages yet'}</span></span>{Number(item.unreadCount) > 0 && <span className="sc-unread-dot" />}</button>)}{!loading && !error && !visible.length && <Empty title="No conversations" text="Buyer messages will appear here when someone contacts your store." />}</div><div className="sc-inbox-footer"><ShieldCheck size={15} /> Live conversations from your account</div></section>
    <section className="sc-thread" aria-label="Conversation">{active ? <><header className="sc-thread-header"><button className="sc-icon-button sc-mobile-back" aria-label="Back to inbox" onClick={() => setSelected(null)}><ArrowLeft size={20} /></button><span className="sc-avatar blue">{initials(active.otherParty?.name || 'User')}</span><div className="sc-thread-person"><h3>{active.otherParty?.name || 'Buyer'}</h3><p>Live buyer conversation</p></div></header><div className="sc-message-history" role="log" aria-live="polite">{messages.map(message => <div key={message.id} className={`sc-message ${message.senderId === active.otherParty?.id ? '' : 'own'}`}><div className="sc-message-row"><div className="sc-bubble">{message.body}</div>{message.senderId !== active.otherParty?.id && <button type="button" className="sc-message-delete" title="Delete message" aria-label="Delete message" onClick={() => void deleteMessage(message.id)}><Trash2 size={13} /></button>}</div><span className="sc-message-time">{message.senderId === active.otherParty?.id ? '' : 'You · '}{relativeTime(message.createdAt)}{message.senderId !== active.otherParty?.id && <Check size={12} />}</span></div>)}<div ref={bottom} />{!messages.length && <Empty title="No messages yet" text="Send the first reply to this buyer." />}</div><form className="sc-composer" onSubmit={send}><div className="sc-compose-box"><textarea aria-label="Write a reply" placeholder={`Reply to ${active.otherParty?.name || 'buyer'}…`} maxLength={4000} rows={1} value={draft} onChange={event => setDraft(event.target.value)} /><div><button aria-label="Send message" title="Send message" className="sc-button primary" disabled={sending || !draft.trim()} type="submit"><Send size={19} /></button></div></div></form></> : requestedBuyerId ? <><header className="sc-thread-header"><span className="sc-avatar blue">B</span><div className="sc-thread-person"><h3>Buyer</h3><p>Start a live conversation</p></div></header><div className="sc-message-history"><Empty title="Start the conversation" text="Send a message to this buyer about the order." /></div><form className="sc-composer" onSubmit={startConversation}><div className="sc-compose-box"><textarea aria-label="Write a message" placeholder="Write a message to the buyer…" maxLength={4000} rows={1} value={draft} onChange={event => setDraft(event.target.value)} /><div><button aria-label="Send message" className="sc-button primary" disabled={sending || !draft.trim()} type="submit"><Send size={19} /></button></div></div></form></> : <Empty title="Your live inbox" text="Select a buyer conversation to read and reply." />}</section>
  </div></div>;
}

type Notification = { id: number; type: string; title: string; body: string; createdAt: string; readAt?: string | null };
export function NotificationsPage() {
  const [items, setItems] = useState<Notification[]>([]); const [query, setQuery] = useState(''); const [unreadOnly, setUnreadOnly] = useState(false); const [loading, setLoading] = useState(true);
  const load = async () => { const response = await fetch(`${API}/api/notifications`, { headers: authHeaders() }); if (response.ok) { const data = await response.json(); setItems(Array.isArray(data.notifications) ? data.notifications : []); } setLoading(false); };
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 10000); return () => window.clearInterval(timer); }, []);
  const unread = items.filter(item => !item.readAt).length; const visible = items.filter(item => (!unreadOnly || !item.readAt) && `${item.title} ${item.body} ${item.type}`.toLowerCase().includes(query.toLowerCase()));
  const markRead = async (id: number) => { await fetch(`${API}/api/notifications/read`, { method: 'POST', headers: authHeaders(true), body: JSON.stringify({ id }) }); setItems(old => old.map(item => item.id === id ? { ...item, readAt: new Date().toISOString() } : item)); };
  const markAll = async () => { await fetch(`${API}/api/notifications/read-all`, { method: 'POST', headers: authHeaders(true) }); setItems(old => old.map(item => ({ ...item, readAt: new Date().toISOString() }))); };
  return <div className="sc-comms sc-notifications notification-center"><div className="nc-heading"><div><div className="nc-kicker"><Bell size={14} /> ACTIVITY CENTER</div><h2>Notifications<span>{unread}</span></h2><p>Your live orders, conversations, and store updates.</p></div><button className="nc-mark-all" disabled={!unread} onClick={markAll}><CheckCheck size={17} /> Mark all as read</button></div><section className="nc-panel" aria-label="Notifications"><div className="nc-toolbar"><div className="nc-view-switch"><button aria-pressed={!unreadOnly} className={!unreadOnly ? 'active' : ''} onClick={() => setUnreadOnly(false)}>All updates</button><button aria-pressed={unreadOnly} className={unreadOnly ? 'active' : ''} onClick={() => setUnreadOnly(true)}>Unread <span>{unread}</span></button></div><label className="sc-search"><Search size={17} /><input aria-label="Search notifications" placeholder="Search notifications…" value={query} onChange={event => setQuery(event.target.value)} /></label></div><div className="nc-group"><div className="nc-group-label">Live activity<span>{visible.length} updates</span></div>{loading ? <Empty title="Loading notifications" text="Checking your live account activity…" /> : visible.map(item => <article key={item.id} className={`nc-item ${!item.readAt ? 'unread' : ''}`} onClick={() => !item.readAt && void markRead(item.id)}><span className="nc-event-icon blue">{item.type === 'order' ? <Package size={20} /> : <MessageSquare size={20} />}</span><div className="nc-item-content"><div className="nc-item-title"><h3>{item.title}</h3>{!item.readAt && <span className="nc-new" aria-label="Unread" />}</div><p>{item.body}</p><div className="nc-item-bottom"><span className="nc-category">{item.type}</span><span className="nc-time">{relativeTime(item.createdAt)}</span></div></div><button className={`nc-read-button ${item.readAt ? 'is-read' : ''}`} title={item.readAt ? 'Read' : 'Mark as read'} aria-label="Mark notification as read" onClick={event => { event.stopPropagation(); void markRead(item.id); }}><Check size={16} /></button></article>)}{!loading && !visible.length && <Empty title={unreadOnly ? 'You are all caught up' : 'No notifications'} text="Real account activity will appear here." />}</div></section><p className="nc-endnote"><ShieldCheck size={14} /> Live notifications from your seller account</p></div>;
}
